# Numpy

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
print("Original array:", arr1)
print("Array shape:", arr1.shape)
print(type(arr1))

Original array: [1 2 3]
Array shape: (3,)
<class 'numpy.ndarray'>


## Attributes of numpy arrays

In [5]:
## Attributes of numpy arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"Array:\n{arr}")
print(f"Array shape: {arr.shape}")
print(f"Number of dimensions: {arr.ndim}")
print(f"Size (number of elements): {arr.size}")
print(f"Data type of elements: {arr.dtype}")
print(f"Item size (in bytes): {arr.itemsize}")

Array:
[[1 2 3]
 [4 5 6]]
Array shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type of elements: int64
Item size (in bytes): 8


## Numpy Vectorized Operation

In [6]:
### Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element-wise addition
arr_sum = arr1 + arr2
print(f"Element-wise addition:\n{arr_sum}")

### Element-wise multiplication
arr_product = arr1 * arr2
print(f"Element-wise multiplication:\n{arr_product}")

### Element-wise substraction
arr_diff = arr2 - arr1
print(f"Element-wise subtraction:\n{arr_diff}")

### Element-wise division
arr_div = arr1 / arr2
print(f"Element-wise division:\n{arr_div}")

Element-wise addition:
[11 22 33 44 55]
Element-wise multiplication:
[ 10  40  90 160 250]
Element-wise subtraction:
[ 9 18 27 36 45]
Element-wise division:
[0.1 0.1 0.1 0.1 0.1]


### Statistical oncepts-Normalization 

In [15]:
### Statistical operations
### to have mean and standard deviation
arr3 = np.array([1, 2, 3, 4, 5])

### Calcualte the mean and standard deviation
mean_value = np.mean(arr3)
std_value = np.std(arr3)
print(f"Mean: {mean_value}, \nStandard Deviation: {std_value}")

### Normalize the array
normalized_arr = (arr3 - mean_value) / std_value
print(f"Normalized array:\n{normalized_arr}")

Mean: 3.0, 
Standard Deviation: 1.4142135623730951
Normalized array:
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Logical Operation

In [20]:
### Logical operations
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr4>5)
print(arr4[arr4 > 5])  # Filtering elements greater than 5
print(arr4[(arr4 > 5) & (arr4 < 9)])  # Filtering elements between 5 and 9
print(arr4)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
